//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Feb 24 17:58:52 2023 by ROOT version 6.14/06)
//      from the StreamerInfo in file ../run-edep-sim/output/MiniRun1_1E19_RHC_nu/EDEPSIM/g4numiv6_minervame_me000z-200i_0_0001.000.EDEPSIM.root
//////////////////////////////////////////////////////////


#ifndef TG4Event_h
#define TG4Event_h
class TG4Event;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "TG4PrimaryVertex.h"
#include "TG4Trajectory.h"
#include <map>
namespace std {} using namespace std;
#include "TG4HitSegment.h"
#ifdef __MAKECINT__
#pragma link C++ class pair<string,vector<TG4HitSegment> >+;
#endif

class TG4Event : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         RunId;       //
   int         EventId;     //
   vector<TG4PrimaryVertex> Primaries;    // (TG4PrimaryVertex)
   vector<TG4Trajectory>    Trajectories;    // (TG4Trajectory)
   std::vector<std::pair<std::string,std::vector<TG4HitSegment> > > SegmentDetectors;    //

   TG4Event();
   TG4Event(const TG4Event & );
   virtual ~TG4Event();

   ClassDef(TG4Event,2); // Generated by MakeProject.
};
#endif
