//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Feb 24 17:58:52 2023 by ROOT version 6.14/06)
//      from the StreamerInfo in file ../run-edep-sim/output/MiniRun1_1E19_RHC_nu/EDEPSIM/g4numiv6_minervame_me000z-200i_0_0001.000.EDEPSIM.root
//////////////////////////////////////////////////////////


#ifndef TG4PrimaryParticle_h
#define TG4PrimaryParticle_h
class TG4PrimaryParticle;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"

class TG4PrimaryParticle : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         TrackId;     //
   string      Name;        //
   int         PDGCode;     //
   TLorentzVector Momentum;    //

   TG4PrimaryParticle();
   TG4PrimaryParticle(const TG4PrimaryParticle & );
   virtual ~TG4PrimaryParticle();

   ClassDef(TG4PrimaryParticle,2); // Generated by MakeProject.
};
#endif
