//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Feb 24 17:58:52 2023 by ROOT version 6.14/06)
//      from the StreamerInfo in file ../run-edep-sim/output/MiniRun1_1E19_RHC_nu/EDEPSIM/g4numiv6_minervame_me000z-200i_0_0001.000.EDEPSIM.root
//////////////////////////////////////////////////////////


#ifndef TG4PrimaryVertex_h
#define TG4PrimaryVertex_h
class TG4PrimaryVertex;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "TG4PrimaryParticle.h"
#include "TG4PrimaryVertex.h"
#include "TLorentzVector.h"
#include <string>

class TG4PrimaryVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<TG4PrimaryParticle> Particles;    //
   vector<TG4PrimaryVertex>   Informational;    //
   TLorentzVector             Position;         //
   string                     GeneratorName;    //
   string                     Reaction;         //
   string                     Filename;         //
   int                        InteractionNumber;    //
   float                      CrossSection;         //
   float                      DiffCrossSection;     //
   float                      Weight;               //
   float                      Probability;          //

   TG4PrimaryVertex();
   TG4PrimaryVertex(const TG4PrimaryVertex & );
   virtual ~TG4PrimaryVertex();

   ClassDef(TG4PrimaryVertex,3); // Generated by MakeProject.
};
#endif
