//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Fri Feb 24 17:58:52 2023 by ROOT version 6.14/06)
//      from the StreamerInfo in file ../run-edep-sim/output/MiniRun1_1E19_RHC_nu/EDEPSIM/g4numiv6_minervame_me000z-200i_0_0001.000.EDEPSIM.root
//////////////////////////////////////////////////////////


#ifndef TG4TrajectoryPoint_h
#define TG4TrajectoryPoint_h
class TG4TrajectoryPoint;

#include "Rtypes.h"
#include "TObject.h"
#include "TLorentzVector.h"
#include "TVector3.h"

class TG4TrajectoryPoint : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TLorentzVector Position;    //
   TVector3       Momentum;    //
   int            Process;     //
   int            Subprocess;    //

   TG4TrajectoryPoint();
   TG4TrajectoryPoint(const TG4TrajectoryPoint & );
   virtual ~TG4TrajectoryPoint();

   ClassDef(TG4TrajectoryPoint,2); // Generated by MakeProject.
};
#endif
