* References
** Callum's GENIE -> dumpTree
/global/u2/c/cwilk/2x2_evt_gen
** Peter's larnd-sim
/global/cfs/cdirs/dune/users/pmadigan/larpix/larpix-software/larnd-sim

* Remember?
- Disable mpich module in shifter
- export HDF5_USE_FILE_LOCKING=FALSE
- source /environment?

* Misc
- Should we take the 2x2 geometry from (1) /global/u2/c/cwilk/2x2_evt_gen or (2) /global/cfs/cdirs/dune/users/2x2EventGeneration/inputs/NuMI? (2) has a smaller (=faster?) world volume, and some extra SensDets for the cryostat, whereas (1) has more SensDets for MINERvA (fibers). Go with (2) for now, since that seems to be what Callum actually used. There's also the version in /global/u2/c/cwilk/2x2_evt_gen/inputs, which seems to have less "stuff" (SensDets etc.) than the other two versions.
- Similarly, should we take 2x2_beam_cherry.mac from (1) or (2)? (2) adds "/edep/phys/ionizationModel 0", which apparently loads NEST, allowing consideration of nuclei that aren't Ar. So let's go with (2) (again, apparently what Callum used).
- Should we be using the same tune when generating maxpath? Default (for maxpath) is G18_02a_00_000 but elsewhere we use G18_10a_02_11a. UPDATE: We now explicitly specify the tune when generating maxpath.
