## Physics changes

## Not everything is LAr
/edep/phys/ionizationModel 0

/edep/db/set/neutronThreshold 0 MeV
/edep/db/set/lengthThreshold 0 mm
/edep/db/set/gammaThreshold 0 MeV

# This ensures that each hit segment in the LAr is only associated with one
# trajectory. It must be run BEFORE /edep/update.
# https://github.com/DUNE/2x2_sim/issues/20
/edep/hitSeparation TPCActive_shape -1 mm

/edep/update

/generator/kinematics/set rooTracker
# input is set in slurm_task.sh
# /generator/kinematics/rooTracker/input gntp.0.roo.cherry.root
/generator/position/set free
/generator/time/set free
/generator/count/fixed/number 1
/generator/count/set fixed
/generator/add
