batch_size: 5000            # track segments
event_batch_size: 2          # tpcs
write_batch_size: 1          # batches
is_spill_sim: 0              # boolean
spill_period: 1.2e6          # microseconds
event_separator: 'vertexID'  # 'vertexID' or 'eventID'
